# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CareBare < Formula
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/Blue-Bear-Security/care-bare"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.1.1/care-bare_0.1.1_darwin_amd64.tar.gz"
      sha256 "5fd8269da68af75f58ab5bb2bdcbcceb3893c9b1001cb111bf637a1cd3760536"

      define_method(:install) do
        bin.install "care-bare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.1.1/care-bare_0.1.1_darwin_arm64.tar.gz"
      sha256 "d7496e71783726a39a8a4a574fef10d5704035b44a36eec33f5ea449f53ebebe"

      define_method(:install) do
        bin.install "care-bare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.1.1/care-bare_0.1.1_linux_amd64.tar.gz"
      sha256 "ee6f71b8fb7e390e731cd51a65c48b34a8e57ba49cb80dfeabc6dec76ce826b6"
      define_method(:install) do
        bin.install "care-bare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.1.1/care-bare_0.1.1_linux_arm64.tar.gz"
      sha256 "f86dc78585f7ac5ac2ba1173cb538b306a97333419d5dd2907fb0341e0b71022"
      define_method(:install) do
        bin.install "care-bare"
      end
    end
  end

  test do
    system "#{bin}/care-bare", "version"
  end
end
